### ISSUE TITLE
Front-end Route | dashboard

### ISSUE THREAD

**Issue by ahmadysalah** [GSG-G8/applicants-system#43]
Front-end Route | dashboard heavy_check_mark

- [ ]  Route
- /dashboard: dashboard for admin front end page
- protected: true

- [ ] UI

![image](https://user-images.githubusercontent.com/44713857/77896167-87ec1d80-7280-11ea-9a6d-ba88685fdfd0.png)

**Comment by Asmaathabet** [comment]
Duplicated Issue
