### ISSUE TITLE
Back-end Route| Opened & submitted applications 

### ISSUE THREAD

**Issue by Asmaathabet** [GSG-G8/applicants-system#81]
## Back-end Route: 
get all Opened and submitted application by fetching queryparams from database.

#### Method : GET 

---

#### Main Things : 
- [ ] Database
- [ ] Response
- [ ] Test

---

#### Database :
 Retrieve all applicants data that their applications agree with entered queryparams and suitable with it.

---
#### Response : 
Response may be success or error :
* Error :
```javascript
    {
    error: "There is No applications",
    "Status-Code": 400
    }
```
* Success
```javascript
    {
    "Status-Code": 200,
    "message" : "success" , 
    data: [
      {applicant 1 data},
      {applicant 2 data}
       . 
       .
       .
        ] ,
 }   
 
```
---
#### Test : 
* Route : 
  Test `/applicants?queryparams → subtmitedDate={true/false}&codewars >5, freecodecamp>220&coveredAllTopics=true` Route  by testing params and  all the expected cases for correct retrieve from the server.

**Comment by ahmadysalah** [comment]
`Test /applicants?queryparams → subtmitedDate={true/false}&codewars >5,`

codeware I think should be <=5

**Comment by alidah0** [comment]
@ahmadysalah yeah, this is just an example
