### ISSUE TITLE
update Login  Response 

### ISSUE THREAD

**Issue by Asmaathabet** [GSG-G8/applicants-system#97]
As an applicant , when you Logged in there is no need to send all this data in the response, so try to elimenate it & display only the main things, like email, full name, location, avatar [the data that  the applicant used in sign up ]
![login](https://user-images.githubusercontent.com/29041512/78640028-b0df6480-78b7-11ea-8388-2d507ca02a84.png)

**Comment by ahmadysalah** [comment]
in Progress..
